services:
  # MS SQL
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server
    environment:
      SA_PASSWORD: "SpiLlett777!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    networks:
      - backend-network

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend-network

  # StockService
  stock-service:
    build:
      context: .
      dockerfile: Backend/StockService/Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: "Server=db,1433;Database=StockDb;User Id=sa;Password=SpiLlett777!;TrustServerCertificate=True;"
      ASPNETCORE_ENVIRONMENT: "Development"
    ports:
      - "5001:8080"
    depends_on:
      - db
      - rabbitmq
    networks:
      - backend-network

  # PortfolioService
  portfolio-service:
    build:
      context: .
      dockerfile: Backend/PortfolioService/Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: "Server=db,1433;Database=PortfolioDb;User Id=sa;Password=SpiLlett777!;TrustServerCertificate=True;"
      ASPNETCORE_ENVIRONMENT: "Development"
    ports:
      - "5002:8080"
    depends_on:
      - db
      - rabbitmq
    networks:
      - backend-network

  # AccountService
  account-service:
    build:
      context: .
      dockerfile: Backend/AccountService/Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: "Server=db,1433;Database=AccountDb;User Id=sa;Password=SpiLlett777!;TrustServerCertificate=True;"
      ASPNETCORE_ENVIRONMENT: "Development"
    ports:
      - "5003:8080"
    depends_on:
      - db
      - rabbitmq
    networks:
      - backend-network

  # Frontend
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - stock-service
      - portfolio-service
      - account-service
    networks:
      - backend-network

volumes:
  mssql-data:

networks:
  backend-network:
    driver: bridge
